# ============================================
# TERRAFORM OUTPUTS
# Use these values in application code
# ============================================

# ============================================
# ENVIRONMENT INFO
# ============================================

output "environment" {
  description = "Current environment"
  value       = var.environment
}

output "aws_region" {
  description = "AWS region"
  value       = var.aws_region
}

output "is_localstack" {
  description = "Whether running on LocalStack"
  value       = var.localstack_endpoint != ""
}

# ============================================
# S3 BUCKETS
# ============================================

output "s3_bucket_raw_data_name" {
  description = "S3 bucket name for raw market data"
  value       = aws_s3_bucket.trading_raw_data.bucket
}

output "s3_bucket_raw_data_arn" {
  description = "ARN of raw data bucket"
  value       = aws_s3_bucket.trading_raw_data.arn
}

output "s3_bucket_models_name" {
  description = "S3 bucket name for ML models"
  value       = aws_s3_bucket.trading_models.bucket
}

output "s3_bucket_models_arn" {
  description = "ARN of models bucket"
  value       = aws_s3_bucket.trading_models.arn
}

# ============================================
# KINESIS STREAMS
# ============================================

output "kinesis_stream_name" {
  description = "Kinesis stream name for market trades"
  value       = aws_kinesis_stream.market_trades.name
}

output "kinesis_stream_arn" {
  description = "ARN of market trades stream"
  value       = aws_kinesis_stream.market_trades.arn
}

output "kinesis_shard_count" {
  description = "Number of Kinesis shards"
  value       = aws_kinesis_stream.market_trades.shard_count
}

# ============================================
# SUMMARY
# ============================================

output "setup_summary" {
  description = "Summary of Phase 1 infrastructure"
  value = {
    environment      = var.environment
    region           = var.aws_region
    is_localstack    = var.localstack_endpoint != ""
    s3_buckets       = 2
    kinesis_streams  = 1
    total_resources  = 3
  }
}

# ============================================
# .ENV FORMAT OUTPUT
# Copy these to your .env file
# ============================================

output "env_file_format" {
  description = "Environment variables for application (.env format)"
  value = <<-EOT
# Generated by Terraform - Phase 1
# Copy these to your .env.local file

ENVIRONMENT=${var.environment}
AWS_REGION=${var.aws_region}
AWS_ENDPOINT_URL=${var.localstack_endpoint}

# S3 Buckets
S3_BUCKET_RAW_DATA=${aws_s3_bucket.trading_raw_data.bucket}
S3_BUCKET_MODELS=${aws_s3_bucket.trading_models.bucket}

# Kinesis Streams
KINESIS_STREAM_MARKET_TRADES=${aws_kinesis_stream.market_trades.name}
EOT
}
